// src/data/solicitacao.js
export const solicitacao = [
  {
    "_id": "1",
    "Solicitante": "Antonio Luiz Amaro",
    "NM": "73388",
    "Componente": "Peças Avulsas",
    "Peça Identificada": "Não",
    "Data Entrada": "2023-10-01",
    "Hora Entrada": "10:00",
    "Hora Saída": "12:00",
    "Data Saída": "2023-10-02",
    "Lavador": "Encerrado",
    "Prioridade": "Normal",
    "Setor": "Montagem"
  },
  {
    "_id": "2",
    "Solicitante": "Igor de Paula",
    "NM": "72833",
    "Componente": "Peças Avulsas",
    "Peça Identificada": "Não",
    "Data Entrada": "2023-10-01",
    "Hora Entrada": "10:00",
    "Hora Saída": "12:00",
    "Data Saída": "2023-10-02",
    "Lavador": "Encerrado",
    "Prioridade": "Normal",
    "Setor": "Montagem"
  },
   {
    "_id": "3",
    "Solicitante": "Isac Junio",
    "NM": "9999",
    "Componente": "Peças Avulsas",
    "Peça Identificada": "Não",
    "Data Entrada": "2023-10-01",
    "Hora Entrada": "10:00",
    "Hora Saída": "12:01",
    "Data Saída": "2023-10-02",
    "Lavador": "Em Andamento",
    "Prioridade": "Normal",
    "Setor": "Montagem"
  },
   {
    "_id": "1",
    "Solicitante": "Antonio Luiz Amaro",
    "NM": "73388",
    "Componente": "Peças Avulsas",
    "Peça Identificada": "Não",
    "Data Entrada": "2023-10-01",
    "Hora Entrada": "10:00",
    "Hora Saída": "12:00",
    "Data Saída": "2023-10-02",
    "Lavador": "Encerrado",
    "Prioridade": "Normal",
    "Setor": "Montagem"
  },
  {
    "_id": "2",
    "Solicitante": "Igor de Paula",
    "NM": "72833",
    "Componente": "Peças Avulsas",
    "Peça Identificada": "Não",
    "Data Entrada": "2023-10-01",
    "Hora Entrada": "10:00",
    "Hora Saída": "12:00",
    "Data Saída": "2023-10-02",
    "Lavador": "Encerrado",
    "Prioridade": "Normal",
    "Setor": "Montagem"
  },
   {
    "_id": "3",
    "Solicitante": "Isac Junio",
    "NM": "9999",
    "Componente": "Peças Avulsas",
    "Peça Identificada": "Não",
    "Data Entrada": "2023-10-01",
    "Hora Entrada": "10:00",
    "Hora Saída": "12:01",
    "Data Saída": "2023-10-02",
    "Lavador": "Em Andamento",
    "Prioridade": "Normal",
    "Setor": "Montagem"
  },
];
